ARDUINO_DIR   = /home/take/bin/arduino-1.6.12
#ARDMK_DIR     = /home/take/bin/arduino-1.6.12
AVR_TOOLS_DIR = /home/take/bin/arduino-1.6.12/hardware/tools/avr

BOARD_TAG	= mega
MONITOR_PORT	= /dev/ttyUSB0
ARDUINO_LIBS	= OneWire Adafruit-GFX-Library Adafruit-PCD8544-Nokia-5110-LCD-library SPI

include /home/take/bin/Arduino-Makefile/Arduino.mk

